jblogga/urls.py
from django.conf.urls.defaults import *
from jblogga.toast.views import HomeView, AddBlogEntryView, ViewBlogEntryView, DeleteBlogEntryView

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^jbongga/', include('jbongga.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/', include(admin.site.urls)),
    url(r'^$', HomeView.as_view()),
    url(r'^add$', AddBlogEntryView.as_view()),
    url(r'^blog/(?P<key>[\d\w-]+)$', ViewBlogEntryView.as_view()),
    url(r'^delete/(?P<key>[\d\w-]+)$', DeleteBlogEntryView.as_view()),
)

jblogga/toast/models.py
import datetime
from google.appengine.ext import db
from google.appengine.ext.db import BadKeyError


class BlogEntry(db.Model):
    author = db.UserProperty()
    title = db.StringProperty()
    body = db.TextProperty()
    created_at = db.DateTimeProperty()

    @classmethod
    def all_recent(cls):
        q = BlogEntry.all()
        q.order('-created_at')
        return q.fetch(5)

    @classmethod
    def put_blog(cls, author, title, body):
        blog_entry = BlogEntry(author=author, title=title, body=body, created_at=datetime.datetime.now())
        blog_entry.put()

    @classmethod
    def get_blog(cls, key):
        try:
            return db.get(key)
        except BadKeyError:
            return None

    @classmethod
    def delete_blog(cls, key):
        db.delete(key)

jblogga/toast/forms.py
__author__ = 'jez'

from django import forms

class AddBlogEntryForm(forms.Form):

    title = forms.CharField(max_length=128, label='Title: ', widget=forms.TextInput(attrs={'class' : 'input title'}))
    body = forms.CharField(label='Body: ', widget=forms.Textarea(attrs={'class' : 'input tinyedit'}))

class DeleteBlogEntryForm(forms.Form):

    key = forms.CharField(max_length=128, widget=forms.HiddenInput())

jblogga/toast/views.py
# Create your views here.
from django.http import Http404

from django.views.generic.edit import FormView
from jblogga.toast.forms import DeleteBlogEntryForm

from models import BlogEntry
from forms import AddBlogEntryForm
from django.views.generic import TemplateView, View



class HomeView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        """
        add recent blog entries
        """
        context = super(HomeView, self).get_context_data(**kwargs)
        context['blogs'] = [entry for entry in BlogEntry.all_recent()]

        return context

class AddBlogEntryView(FormView):
    template_name = "addnew.html"
    form_class = AddBlogEntryForm
    success_url = '/'

    def form_valid(self, form):
        """
        save the blog and delegate back up to formview for the redirect
        """
        BlogEntry.put_blog(self.request.user,form.cleaned_data['title'],form.cleaned_data['body'])
        return super(AddBlogEntryView, self).form_valid(form)

class ViewBlogEntryView(TemplateView):
    template_name = "full_blog_entry.html"

    def get_context_data(self, **kwargs):
        """
        add recent blog entries
        """
        context = super(ViewBlogEntryView, self).get_context_data(**kwargs)
        blog = BlogEntry.get_blog(kwargs['key'])

        if not blog:
            raise Http404

        context['blog'] = blog

        return context

class DeleteBlogEntryView(FormView):
    template_name = "delete.html"
    form_class = DeleteBlogEntryForm
    success_url = "/"

    def get_initial(self):
        return {'key' : self.kwargs['key']}

    def get_context_data(self, **kwargs):
        """
        fetch the blog that is about to be deleted
        """
        context = super(DeleteBlogEntryView, self).get_context_data(**kwargs)
        blog = BlogEntry.get_blog(self.kwargs['key'])

        if not blog:
            raise Http404

        context['blog'] = blog

        return context

    def form_valid(self, form):
        """
        save the blog and delegate back up to formview for the redirect
        """
        BlogEntry.delete_blog(form.cleaned_data['key'])
        return super(DeleteBlogEntryView, self).form_valid(form)

jblogga/templates/addnew.html
{% extends "base.html" %}

{% block script %}

    <script type="text/javascript" src="/static/tinymce/jscripts/tiny_mce/tiny_mce.js" ></script >
    <script type="text/javascript">
    tinyMCE.init({
            mode : "textareas",
            theme : "advanced",
            plugins : "emotions,spellchecker,advhr,insertdatetime,preview",

            // Theme options - button# indicated the row# only
            theme_advanced_buttons1 : "newdocument,|,bold,italic,underline,|,justifyleft,justifycenter,justifyright,fontselect,fontsizeselect,formatselect",
            theme_advanced_buttons2 : "cut,copy,paste,|,bullist,numlist,|,outdent,indent,|,undo,redo,|,link,unlink,anchor,image,|,code,preview,|,forecolor,backcolor",
            theme_advanced_buttons3 : "insertdate,inserttime,|,spellchecker,advhr,,removeformat,|,sub,sup,|,charmap,emotions",
            theme_advanced_toolbar_location : "top",
            theme_advanced_toolbar_align : "left",
            theme_advanced_statusbar_location : "bottom",
            theme_advanced_resizing : false,
            height: 600,
            width: 600
    });
    </script>


{% endblock %}

{% block body-content %}

    <div id="new-blog">

    {% include "forms/new_blog.html" %}

    </div>

{% endblock %}

jblogga/templates/base.html
<!DOCTYPE HTML>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="/static/css/style.css" />
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>

    <title>Demo</title>

    {% block script %}{% endblock %}
    {% block link %}{% endblock %}
</head>
<body>

<div id="body-wrap">
{%  include "includes/header.html" %}

{% block body-content %}
{% endblock %}

{% include "includes/about.html" %}
</div>

</body>
</html>

jblogga/templates/delete.html
{% extends "base.html" %}

{% block body-content %}

    <div class="blog-delete blog-content ">
    <form method="post">

    <p>Delete this blog entry..are you sure?</p>

    {{ form.key }}

        <input type="submit" value="im a big boy..just do it already" class="button" />
        <div class="clear"></div>

    </form>
    </div>
    <br />

    {% include "includes/blog_entry.html" %}

{%  endblock %}

jblogga/templates/forms/new_blog.html
<form method="post" action="/add" id="login-form">

    <div class="form-row">

        <label for="id_title">title</label>

        {{ form.title }}

    </div>

    <div class="form-row">

    {{ form.body }}
    </div>


    <input type="submit" value="add" class="button" />
    <div class="clear"></div>
</form>

jblogga/templates/full_blog_entry.html
{% extends "base.html" %}
{% load utils %}

{% block body-content %}
{% include "includes/blog_entry.html" %}

    <div class="blog-content">
    {% if user.nickname %}

    {% get_is_editable blog %}
    {%  if can_edit %}
        <a href="/delete/{{ blog.key }}">Delete this entry</a>
    {% endif %}
    {% endif %}
    </div>

{% endblock %}

jblogga/templates/home.html
{%  extends "base.html" %}


{%  block body-content %}


    {% include "includes/all_blogs.html" %}

{% endblock %}

jblogga/templates/includes/about.html
<div class="about-me">
    <div class="blog-content ">
    <p>About me - just hanging here in GAE </p>

    </div>
</div>

jblogga/templates/includes/ajax_loading.html
<div id="loadingDiv"></div>

jblogga/templates/includes/all_blogs.html
{% if blogs %}
{% load utils %}

{% for blog in blogs %}



    {% include "includes/blog_entry.html" %}
{% endfor %}

{% endif %}

jblogga/templates/includes/blog_entry.html
<div class="blog-entry">
    <h2>
        <a href ="/blog/{{ blog.key }}">{{ blog.title }}</a>
    </h2>

    <div class="blog-content">

    <p class="blog-meta">
        <a href="/blog/{{ blog.key }}"></a>
        {{ blog.created_at }} by {{ blog.author }}
    </p>

    <p>
        {{ blog.body|safe }}
    </p>

    </div>
</div>

jblogga/templates/includes/fake_article.html
<div class="blog-entry">
    <h2>
        <a href ="/">Fake blog title</a>
    </h2>

    <div class="blog-content">




    <p class="blog-meta">
        <a href="/">#12345</a>
        10 September 2012
    </p>



    <p>
        SWTOR was definitely a more polished launch than WAR, but arguably WAR was a more complete game.
        Both struggled with RvR in the context of engine performance, but SWTOR is much worse, but SWTOR has now completely removed all RvR. Both struggled with PvP class balance, but SWTOR has serious problems with CC in PvP.

    </p>

       </div

</div>

<div class="blog-entry">
    <h2>
        <a href ="/">Another Fake blog title</a>
    </h2>

    <div class="blog-content">




    <p class="blog-meta">
        <a href="/">#9</a>
        12 September 2012
    </p>



    <p>
        SWTOR was definitely a more polished launch than WAR, but arguably WAR was a more complete game.
        Both struggled with RvR in the context of engine performance, but SWTOR is much worse, but SWTOR has now completely removed all RvR. Both struggled with PvP class balance, but SWTOR has serious problems with CC in PvP.

    </p>

       </div

</div>

jblogga/templates/includes/header.html
<div id="header">
    <h1><a href="/">jbong</a></h1>
    <div id="auth-panel">
    {% if user %}
        {% if user.nickname %}
            <p>{{ user.nickname }}
            <a href="{{ auth_urls.out }}">sign out</a>
            </p>
            <p>
                <a href="/add">+ add new</a>
            </p>
        {% else %}
            <a href="{{ auth_urls.in }}">sign in</a>
        {% endif %}

    {%  else  %}
        <a href="{{ auth_urls.in }}">sign in</a>
    {% endif %}

    </div>
</div>